### ISSUE TITLE
Unhandled Client Exception in lambda_method111

### ISSUE THREAD

**Issue by Cirras** [ethanmoffat/EndlessClient#397]
**What were you doing when the exception occurred?**
I selected a character and was waiting to load into the game.

**What server were you playing on?**
Bones Underground

**Has this crash occurred for you before?**
It's happened consistently on 1.0.472 and 1.0.475.

**Expected behavior (other than it not crashing)?**
The character should load into the game successfully.

**Diagnostic Information**

```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at lambda_method111(Closure, Int32)
   at EOLib.IO.CastTo`1.From[S](S s) in D:\a\1\s\EOLib.IO\Caster.cs:line 22
   at EOLib.IO.Pub.PubRecord.Get[T](PubRecordProperty property) in D:\a\1\s\EOLib.IO\Pub\PubRecord.cs:line 105
   at EOLib.IO.Pub.EIFRecord.get_Type() in D:\a\1\s\EOLib.IO\Pub\EIFRecord.cs:line 9
   at EndlessClient.Rendering.CharacterProperties.CharacterPropertyRendererBuilder.<>c__DisplayClass6_0.<IsWeaponBehindCharacter>b__0(EIFRecord x) in D:\a\1\s\EndlessClient\Rendering\CharacterProperties\CharacterPropertyRendererBuilder.cs:line 78
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at EndlessClient.Rendering.CharacterProperties.CharacterPropertyRendererBuilder.IsWeaponBehindCharacter(CharacterRenderProperties renderProperties) in D:\a\1\s\EndlessClient\Rendering\CharacterProperties\CharacterPropertyRendererBuilder.cs:line 77
   at EndlessClient.Rendering.CharacterProperties.CharacterPropertyRendererBuilder.BuildList(ICharacterTextures textures, CharacterRenderProperties renderProperties)+MoveNext() in D:\a\1\s\EndlessClient\Rendering\CharacterProperties\CharacterPropertyRendererBuilder.cs:line 43
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at EndlessClient.Rendering.Character.CharacterRenderer.DrawToRenderTarget() in D:\a\1\s\EndlessClient\Rendering\Character\CharacterRenderer.cs:line 289
   at EndlessClient.Rendering.Character.CharacterRenderer.Update(GameTime gameTime) in D:\a\1\s\EndlessClient\Rendering\Character\CharacterRenderer.cs:line 190
   at EndlessClient.Rendering.Character.CharacterRendererUpdater.UpdateAllCharacters(GameTime gameTime) in D:\a\1\s\EndlessClient\Rendering\Character\CharacterRendererUpdater.cs:line 120
   at EndlessClient.Rendering.Character.CharacterRendererUpdater.UpdateCharacters(GameTime gameTime) in D:\a\1\s\EndlessClient\Rendering\Character\CharacterRendererUpdater.cs:line 45
   at EndlessClient.Rendering.Map.MapRenderer.Update(GameTime gameTime) in D:\a\1\s\EndlessClient\Rendering\Map\MapRenderer.cs:line 144
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at EndlessClient.GameExecution.EndlessGame.Update(GameTime gameTime) in D:\a\1\s\EndlessClient\GameExecution\EndlessGame.cs:line 202
```

**Comment by ethanmoffat** [comment]
Consistent repro:
1. Delete EIF files from pub directory
2. Attempt to log in to character on BU without weapon equipped
